### PR TITLE
feat(jellyfish-transaction-builder): Fix fees in createVOC

### LINKED ISSUE #3946: creating a DFIP fails
Trying to create a DFIP in the LW fails with "malformed tx vouts (wrong creation fee) (code 16)"

The address has enough DFI and everything seems fine until the tx is sent to ocean. 

Just tried with another address: with 51 DFI UTXOs in the address, the wallet itself says "not enough DFI UTXOs" which is also wrong.

### PR DESCRIPTION
**Pull request by kuegi**
currently, sending a DFIP via jellyfishSDK fails, cause it sets the wrong fees. 
Fixes https://github.com/BirthdayResearch/defichain-wallet/issues/3946

### CODE REVIEW

File: packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts [hunk 1]
```diff
@@ -45,13 +45,13 @@ export class TxnBuilderGovernance extends P2WPKHTxnBuilder {
...
     if (this.network.name === 'mainnet') {
-      creationFee = new BigNumber('100')
+      creationFee = new BigNumber('50')
     }
     if (this.network.name === 'testnet') {
       creationFee = new BigNumber('50')
     }
     if (createVoc.options === 1) {
-      creationFee = new BigNumber('10000')
+      creationFee = new BigNumber('5000')
```
Comment (lykalabrada) [inline packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts]: Hi @kuegi some test is failing, can you help keep this `10000` for testnet, and only set `5000` for mainnet? thanks!

**Review by lykalabrada — CHANGES_REQUESTED** [review]

**Comment by lykalabrada** [comment]
For more info, on chain we have set the following gov attributes:
image

File: packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts (hunk 1 above)
Comment (kuegi) [reply packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts]: on testnet, the 10000 was false before already: 
image
longterm, ocean should provide the govs and this should take it directly from the chain. But IMHo now its most important to get this fixed for users. Cause noone is able to create a VOC via the LW.

Comment (kuegi) [reply packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts:54]: @lykalabrada what network/networkparams are the tests running on?

Comment (kuegi) [reply packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts]: adapted it so that testnet is correct too now (but still hardcoded) and regtest in tests keep working for now.

**Review by lykalabrada — APPROVED** [review]

File: packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts [hunk 2]
```diff
@@ -45,12 +45,18 @@ export class TxnBuilderGovernance extends P2WPKHTxnBuilder {
...
+      } else {
+        creationFee = new BigNumber('50')
+      }
+    } else if (this.network.name === 'testnet') {
+      if (createVoc.options === 1) {
+        creationFee = new BigNumber('50')
+      } else {
+        creationFee = new BigNumber('50')
+      }
+    } else if (createVoc.options === 1) { //so we can test it with regtest params
```
Comment (lykalabrada) [inline packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts]:
```suggestion
    } else if (createVoc.options === 1) {
```

**Review by lykalabrada — CHANGES_REQUESTED** [review]

**Comment by kuegi** [comment]
@lykalabrada can this be merged? Imho it's important to get this in soon so that users can finally make dfips via lightwallet.
This bug is really bad for the governance!

**Review by pierregee — APPROVED** [review]

**Review by lykalabrada — APPROVED** [review]

**Review by fuxingloh — APPROVED** [review]
